# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.1
    hooks:
      - id: check-github-actions
        additional_dependencies:
          - pip_system_certs==4.0
      - id: check-github-workflows
        additional_dependencies:
          - pip_system_certs==4.0
      - id: check-dependabot
        additional_dependencies:
          - pip_system_certs==4.0
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.2.0
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.7.23
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
        # The markdown-link-check can't access internal or private repos, see
        # .markdown_link_check_config.json on how to exclude more than the
        # github.com/arup-group
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        args: [--quiet, --config=.markdown_link_check_config.json]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
        # this should go last since it will fix line endings broken by other tools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: lib/mermaid\.min\.js
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
        exclude: .*\.ipynb$
      - id: check-symlinks
      - id: debug-statements
      - id: fix-byte-order-marker
