[project]
name = "{{cookiecutter.directory_name}}-slides"
version = "0.1.0"
description = "Slides for {{cookiecutter.directory_name}}"
requires-python = ">=3.12"
version = "0.2.0"
requires-python = ">=3.13"
dependencies = [
    "mkslides",
    "qrcode",
    "pillow",
    "playwright",
    "PyPDF2",
    "pre-commit",
    "portend"
]
