---
on: pull_request
name: Build
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: make install
    - run: make html
    - run: make pdf
